name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: dorukgunes/github-auto-assigner@v0.6
        with:
          configuration-path: '.github/auto_assign_config.yml' # Only needed if you use something other than .github/auto_assign.yml
          token: ${{ github.token }}